;;romanToDecimal by Travis Allan
(defun errorcheck (list)
    (setf list3 '(A A A))
    (setf var (list-length list))
    (cond
        ((eq var 1) (return '(A A A)))
    )
    (setf first (nth 0 list))
    (setf second (nth 1 list))
    (cond
        ((eq first 'D)
            (cond
                ((eq second 'M)
                    (return)
                )
            )
            (t (errorcheck (cdr list)))
        )
        ((eq first 'L)
            (cond
                ((eq second 'C)
                    (return)
                )
                ((eq second 'D)
                    (return)
                )
                ((eq second 'M)
                    (return)
                )
                (t (errorcheck (cdr list)))
            )
        )
        ((eq first 'X)
            (cond
                ((eq second 'D)
                    (return)
                )
                ((eq second 'M)
                    (return)
                )
                (t (errorcheck (cdr list)))
            )
        )
        ((eq first 'V)
            (cond
                ((eq second 'C)
                    (return)
                )
                ((eq second 'D)
                    (return)
                )
                ((eq second 'L)
                    (return)
                )
                ((eq second 'M)
                    (return)
                )
                (t (errorcheck (cdr list)))
            )
        )
        ((eq first 'I)
            (cond
                ((eq second 'C)
                    (return)
                )
                ((eq second 'D)
                    (return)
                )
                ((eq second 'L)
                    (return)
                )
                ((eq second 'M)
                    (return)
                )
                (t (errorcheck (cdr list)))
            )
        )
    )
)
(defun romanToDecimal (list)
    (setf list2 (list))
    (setf list3 (list))
    (setf list2 (errorcheck list2))
    (cond
        ((eq list2 'nil)
            (print "error")
        )
        ((eq list2 '(A A A))
            (print "yay")
        )
    )
)





